name: Increment Tag Version
descriptionaa: semantic version
author: Gustavo Venturo
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  list-version-fragment:
    description: 'The versions fragment you want to increment. possible options are [ major | feature | bug | alpha | beta | rc ]'
    required: true
outputs:
  next-version:
    description: 'The incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.list-version-fragmentt }}
