name: Increment Tag Version
descriptionaa: semantic version
author: Gustavo Venturo
branding:
  icon: 'code'
  color: 'purple'
inputs:
  list-version-fragment:
    description: 'The versions fragment you want to increment. possible options are [ major | feature | bug | hotfix | fix ]'
    required: true
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: 'Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.'
    default: ${{ github.token }}
  pulls:
    default: ${{ github.ref_name }}
outputs:
  next-version:
    description: 'The incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.list-version-fragmentt }}
    - ${{ inputs.repository }}
    - ${{ inputs.token }}
    - ${{ inputs.branch }}
